name = input('Você está bem?\n')
print('bom')
name = input('Minha profissao é feia\n')
print('sério qual é?\n')
name = input('Sou garoto de programa!\n')
print('mentira, sério?')
name = input('verdade uai eu faco sistemas de informacao logo programo logo sou garoto de programa\n')
print('bobo e eu aqui pensando besteira haha')
print("TCHAU, TCHAU!!")
